### ISSUE TITLE
Tank falls off the map

### ISSUE THREAD

**Issue by MeerZaheen** [pouladpld/Tank-Mania#12]
# Bug Report

### Scenario
When the tank touches the water, it does not get destroyed but falls (infinite) off the map/level

### Scene
Playground

### Expected
Tank's head should go to 0, hence, destroyed

### Actual
Tanks health still intact and falls off the map

**Comment by poulad** [comment]
This only happens when there only is 1 tank on the scene which mean game is over.

Bug would be fixed when we declare game is over and change the scene.
