### ISSUE TITLE
Menu GUI

### ISSUE THREAD

**Issue by andreghub** [pouladpld/Tank-Mania#17]
### Feature
A Menu should be implemented to guide player through game configurations and assistance.

### Scene
Game Menu Scene

### Description
Buttons:
 - Play
 - Help
 - Quit

**Comment by andreghub** [comment]
@pouladpld What do you think of this first Menu ? Obviously we need background image/fonts/button image/etc.

Please refer to branch issue17

**Comment by poulad** [comment]
Looks pretty good.

- Same font as in GDD should be used for game title
- Bg image doesn't cover the whole area shown by camera. I see gray space on top.

**Comment by andreghub** [comment]
Fonts updated
Canvas resolution fixed
Help Content Inserted based on GDD
