### ISSUE TITLE
Tank spritesheet

### ISSUE THREAD

**Issue by poulad** [pouladpld/Tank-Mania#2]
### Asset
A tank spritesheet with animations.

### Scene
Playground & all levels

### Description
- Muzzle should be detached so animated through code
- Animations:
  - Wheel movement
  - Explosion (die)
  - Getting hit
  - [Nice to have] idle

**Comment by MeerZaheen** [comment]
[Tank Mania sprite 2.zip](https://github.com/pouladpld/Tank-Mania/files/1765052/Tank.Mania.sprite.2.zip)

**Comment by poulad** [comment]
please branch off the `master` into `assets` maybe. Then, import them into a scene and setup animations. Make a PR back to `master`.
