### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by MeerZaheen** [pouladpld/Tank-Mania#23]
### Feature
A pause (ESC) menu so that users are able to pause the game following SETTINGS , QUIT, and RESUME

### Scene
All three levels

### Description
Each player has an option to pause the game by pressing the ESC key on their keyboard which would be the same for all players. 

The player then given the options to either:
QUIZ - where the player quits the game by forfeit and goes to the main menu screen.
SETTINGS - The players are able to change the sound
RESUME - Resume the game

**Comment by poulad** [comment]
I develop this feature w/o sounds option for now. We don't have enough sound assets yet.
