### ISSUE TITLE
Canvas elements misplaced on different screen resolutions

### ISSUE THREAD

**Issue by poulad** [pouladpld/Tank-Mania#27]
### Scenario
Position of canvas elements on screen changes in different resolutions.

### Scene
Playground

### Expected
Elements are in same position. No matter the screen resolution.

### Actual
Elements are misplaced.

**Comment by jharrilim** [comment]
:alien::alien::alien::alien::alien::alien::alien:
https://docs.unity3d.com/Manual/script-CanvasScaler.html
:alien::alien::alien::alien::alien::alien::alien:

**Comment by poulad** [comment]
Fixed on `level1` branch.
