### ISSUE TITLE
Tank Movement

### ISSUE THREAD

**Issue by andreghub** [pouladpld/Tank-Mania#3]
### Feature
Player should be able to move Tank horizontally (left/right) and rotate Tank's muzzle left or right. Tank should be animated to reflect its movement.

### Scene
Playground and all levels

### Description
- Tank Animation must have basic states: Idle, Movement, Muzzle Rotation
- Tank  should move smoothly on irregular terrain

**Comment by poulad** [comment]
Also, weapon should always be shot from the muzzle and at its direction.
