### ISSUE TITLE
Weapon assignment

### ISSUE THREAD

**Issue by andreghub** [pouladpld/Tank-Mania#4]
### Feature
A weapon will be randomly assigned to the player at each turn. 

### Scene
Playground and all levels

### Description
- Weapon is randomly assigned at each turn.
- No weapon inventory
- Weapon assigned must be visible to player by an indicator/icon on the screen

**Comment by MeerZaheen** [comment]
Weapons are based on random selection. Players don't get to choose the weapon.

**Comment by pouladpld** [comment]
@andreghub Please edit your post.

- Weapon is randomly assign at each turn.
- No weapon inventory
