### ISSUE TITLE
Tank Shooting

### ISSUE THREAD

**Issue by andreghub** [pouladpld/Tank-Mania#5]
### Feature
Tank should be able to shoot any direction based on projectile arc. They way to fire is to press and hold the space bar key in order to charge the meter – the higher the meter, the longer the projectile shot.

### Scene
Playground & all levels

### Description
- Charging meter
- Projectile arc
- Shooting animation
- Damage reaction on terrain, object and other tanks

**Comment by poulad** [comment]
I break this feature request into smaller deliverables: #10
